# Generated by Django 2.0.2 on 2018-10-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('shows_played', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_address', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('show_time', models.CharField(max_length=10)),
                ('show_age', models.CharField(max_length=5)),
                ('show_price', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot.Press'),
        ),
        migrations.AddField(
            model_name='band',
            name='shows',
            field=models.ManyToManyField(to='pilot.Show'),
        ),
    ]
