# Generated by Django 2.0.2 on 2018-10-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='show_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='show_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
