# Generated by Django 2.0.2 on 2018-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_auto_20181019_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='website',
            field=models.CharField(default='www.google.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='show',
            name='freshtix',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
