# Generated by Django 2.0.2 on 2018-10-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0006_auto_20181019_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='website',
            field=models.CharField(default='.', max_length=500),
        ),
    ]
