# Generated by Django 2.0.2 on 2018-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0007_auto_20181019_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='bandcamp_name',
            field=models.CharField(default='  ', max_length=200),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(default='  ', max_length=50),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(default='  ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_address_city_state',
            field=models.CharField(default='  ', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_address_street',
            field=models.CharField(default='  ', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(default='  ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(default='  ', max_length=50),
        ),
        migrations.AlterField(
            model_name='press',
            name='description',
            field=models.CharField(default='  ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='press',
            name='name',
            field=models.CharField(default='  ', max_length=50),
        ),
        migrations.AlterField(
            model_name='press',
            name='website',
            field=models.CharField(default='  ', max_length=500),
        ),
        migrations.AlterField(
            model_name='show',
            name='age',
            field=models.CharField(default='  ', max_length=5),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default='  '),
        ),
        migrations.AlterField(
            model_name='show',
            name='day',
            field=models.CharField(default='  ', max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.CharField(default='  ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.CharField(default='  ', max_length=5),
        ),
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.CharField(default='  ', max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(default='  ', max_length=200),
        ),
    ]
