# Generated by Django 2.0.2 on 2018-10-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0008_auto_20181019_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_address_city_state',
            new_name='address_city_state',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_address_street',
            new_name='address_street',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='name',
        ),
    ]
