# Generated by Django 2.0.2 on 2018-10-19 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0012_auto_20181019_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 19, 19, 25, 36, 999457, tzinfo=utc)),
        ),
    ]
