# Generated by Django 2.0.2 on 2018-10-23 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0013_auto_20181019_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 23, 22, 22, 31, 974441, tzinfo=utc)),
        ),
    ]
