# Generated by Django 2.0.2 on 2018-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0014_auto_20181023_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.CharField(default='  ', max_length=10),
        ),
    ]
